name: TestBotApplicationPublisher
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master 
    - uses: azure/login@v1 
      with: 
        creds: ${{ secrets.GGROUPP_AZURE_CREDENTIALS_TEST }}

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ggrouppinternalsupportbotappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3afd9b79227743e7a1d17ff4a6148673 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ab3203b221c4ddbb88a95c97099f9ad }}

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    - name: Publish Application.csproj
      run: dotnet publish ./src/*/Application.csproj -c Release -o './docker/publish'

    - name: 'Run Azure webapp deploy action using azure credentials' 
      uses: azure/webapps-deploy@v2 
      with:  
        app-name: ggroupp-test-internal-support-bot-webapp
        package: './docker' 
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ggrouppinternalsupportbotappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3afd9b79227743e7a1d17ff4a6148673 }}/internal-support-bot-app-test-image:${{ github.sha }}
        file: ./docker/Dockerfile

    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ggroupp-test-internal-support-bot-webapp'
        slot-name: 'test'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3d21d7e3a609408693fafcc19a0e6cb6 }}
        images: 'ggrouppinternalsupportbotappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3afd9b79227743e7a1d17ff4a6148673 }}/internal-support-bot-app-test-image:${{ github.sha }}'

    - name: Azure Logout 
      run: |
        az logout
