name: BuildAndPushDockerImage
on:
  page_build:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master 
    - uses: azure/login@v1 
      with: 
        creds: ${{ secrets.GGROUPP_AZURE_CREDENTIALS_TEST }}

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ggrouppinternalsupportbotappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3afd9b79227743e7a1d17ff4a6148673 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ab3203b221c4ddbb88a95c97099f9ad }}

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    - name: Publish Application.csproj
      run: dotnet publish ./src/*/Application.csproj -c Release -o './docker/publish'
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ggrouppinternalsupportbotappregistry.azurecr.io/internal-support-bot-app-image:${{ steps.vars.outputs.tag }}
        file: ./docker/Dockerfile
